export type Language = 'ar' | 'en';
export type Style = 'formal' | 'omani';
export type Mode = 'manual' | 'auto';

export interface Agent {
  id: number;
  nameAr: string;
  nameEn: string;
  specialtyAr: string;
  specialtyEn: string;
  contributionAr: string;
  contributionEn: string;
  triggerAr: string;
  triggerEn: string;
  icon: string;
  category: 'global' | 'oman';
  color: string;
}

export const AGENTS: Agent[] = [
  {
    id: 1,
    nameAr: "المبتكر",
    nameEn: "Innovator",
    specialtyAr: "توليد أفكار خارج الصندوق",
    specialtyEn: "Out-of-the-box thinking",
    contributionAr: "يقدم زوايا إبداعية غير تقليدية للمشروع.",
    contributionEn: "Provides unconventional creative angles for the project.",
    triggerAr: "عندما يحتاج المشروع لقفزة إبداعية.",
    triggerEn: "When the project needs a creative leap.",
    icon: "Lightbulb",
    category: 'global',
    color: "#f59e0b"
  },
  {
    id: 2,
    nameAr: "المهندس التقني",
    nameEn: "Technical Engineer",
    specialtyAr: "البنية التحتية والتقنيات",
    specialtyEn: "Infrastructure and Technologies",
    contributionAr: "يحدد المتطلبات التقنية والأدوات اللازمة.",
    contributionEn: "Identifies technical requirements and necessary tools.",
    triggerAr: "عند مناقشة كيفية بناء الفكرة تقنياً.",
    triggerEn: "When discussing how to build the idea technically.",
    icon: "Settings",
    category: 'global',
    color: "#3b82f6"
  },
  {
    id: 3,
    nameAr: "مطور البرمجيات",
    nameEn: "Software Developer",
    specialtyAr: "البرمجة والتنفيذ الرقمي",
    specialtyEn: "Programming and Digital Execution",
    contributionAr: "يركز على قابلية التنفيذ البرمجي وتجربة المستخدم التقنية.",
    contributionEn: "Focuses on software feasibility and technical user experience.",
    triggerAr: "عند الحديث عن التطبيقات والمنصات الرقمية.",
    triggerEn: "When talking about apps and digital platforms.",
    icon: "Code",
    category: 'global',
    color: "#10b981"
  },
  {
    id: 4,
    nameAr: "خبير الذكاء الاصطناعي",
    nameEn: "AI Specialist",
    specialtyAr: "تكامل تقنيات الذكاء الاصطناعي",
    specialtyEn: "AI Integration",
    contributionAr: "يقترح نماذج الذكاء الاصطناعي المناسبة لتعزيز الفكرة.",
    contributionEn: "Suggests suitable AI models to enhance the idea.",
    triggerAr: "عند البحث عن طرق لأتمتة العمليات بذكاء.",
    triggerEn: "When looking for ways to intelligently automate processes.",
    icon: "Cpu",
    category: 'global',
    color: "#8b5cf6"
  },
  {
    id: 5,
    nameAr: "محلل نموذج العمل",
    nameEn: "Business Model Analyst",
    specialtyAr: "الاستدامة المالية والربحية",
    specialtyEn: "Financial Sustainability and Profitability",
    contributionAr: "يحلل كيف يمكن للفكرة أن تدر دخلاً وتستمر مالياً.",
    contributionEn: "Analyzes how the idea can generate income and sustain financially.",
    triggerAr: "عند مناقشة الجوانب التجارية والربحية.",
    triggerEn: "When discussing commercial and profitability aspects.",
    icon: "BarChart3",
    category: 'global',
    color: "#ec4899"
  },
  {
    id: 6,
    nameAr: "محامي المستخدم",
    nameEn: "User Advocate",
    specialtyAr: "تجربة المستخدم واحتياجاته",
    specialtyEn: "User Experience and Needs",
    contributionAr: "يضمن أن الفكرة تحل مشكلة حقيقية للمستخدم النهائي.",
    contributionEn: "Ensures the idea solves a real problem for the end user.",
    triggerAr: "عندما تبدو الفكرة معقدة جداً للمستخدم العادي.",
    triggerEn: "When the idea seems too complex for the average user.",
    icon: "UserCheck",
    category: 'global',
    color: "#06b6d4"
  },
  {
    id: 7,
    nameAr: "محلل السوق",
    nameEn: "Market Analyst",
    specialtyAr: "دراسة المنافسين والتوجهات",
    specialtyEn: "Competitor and Trend Analysis",
    contributionAr: "يقدم بيانات عن السوق والفرص المتاحة عالمياً.",
    contributionEn: "Provides data on the market and globally available opportunities.",
    triggerAr: "عند مقارنة الفكرة بما هو موجود حالياً.",
    triggerEn: "When comparing the idea with what currently exists.",
    icon: "TrendingUp",
    category: 'global',
    color: "#f43f5e"
  },
  {
    id: 8,
    nameAr: "محلل المخاطر",
    nameEn: "Risk Analyst",
    specialtyAr: "تحديد التحديات والعقبات",
    specialtyEn: "Identifying Challenges and Obstacles",
    contributionAr: "يسلط الضوء على نقاط الضعف والمخاطر المحتملة.",
    contributionEn: "Highlights potential weaknesses and risks.",
    triggerAr: "عندما يبدو الحماس للفكرة مفرطاً دون واقعية.",
    triggerEn: "When enthusiasm for the idea seems excessive without realism.",
    icon: "ShieldAlert",
    category: 'global',
    color: "#ef4444"
  },
  {
    id: 9,
    nameAr: "مخطط العمليات",
    nameEn: "Operations Planner",
    specialtyAr: "سير العمل واللوجستيات",
    specialtyEn: "Workflow and Logistics",
    contributionAr: "يضع خارطة طريق لتنفيذ الفكرة على أرض الواقع.",
    contributionEn: "Creates a roadmap for implementing the idea on the ground.",
    triggerAr: "عند الانتقال من مرحلة الفكرة إلى مرحلة التنفيذ.",
    triggerEn: "When moving from the idea stage to the execution stage.",
    icon: "ClipboardList",
    category: 'global',
    color: "#6366f1"
  },
  {
    id: 10,
    nameAr: "خبير التوسع",
    nameEn: "Scalability Expert",
    specialtyAr: "النمو والانتشار العالمي",
    specialtyEn: "Growth and Global Reach",
    contributionAr: "يفكر في كيفية تكبير المشروع ليخدم ملايين المستخدمين.",
    contributionEn: "Thinks about how to scale the project to serve millions of users.",
    triggerAr: "عندما تنجح الفكرة في نطاق ضيق ونريد توسيعها.",
    triggerEn: "When the idea succeeds on a small scale and we want to expand it.",
    icon: "Maximize",
    category: 'global',
    color: "#a855f7"
  },
  {
    id: 11,
    nameAr: "محلل الجدوى العماني",
    nameEn: "Oman Feasibility Analyst",
    specialtyAr: "ملاءمة الفكرة للسوق العماني",
    specialtyEn: "Suitability for the Omani Market",
    contributionAr: "يحلل مدى تقبل المجتمع العماني للفكرة وجدواها محلياً.",
    contributionEn: "Analyzes the Omani society's acceptance of the idea and its local feasibility.",
    triggerAr: "عند البدء في تخصيص الفكرة لسلطنة عمان.",
    triggerEn: "When starting to customize the idea for the Sultanate of Oman.",
    icon: "MapPin",
    category: 'oman',
    color: "#14b8a6"
  },
  {
    id: 12,
    nameAr: "مستشار التشريعات",
    nameEn: "Regulation Advisor",
    specialtyAr: "القوانين والأنظمة في عمان",
    specialtyEn: "Laws and Regulations in Oman",
    contributionAr: "يوضح القوانين العمانية المتعلقة بالمشروع والتراخيص المطلوبة.",
    contributionEn: "Explains Omani laws related to the project and required licenses.",
    triggerAr: "عند الحديث عن الجوانب القانونية والترخيص.",
    triggerEn: "When talking about legal and licensing aspects.",
    icon: "Gavel",
    category: 'oman',
    color: "#78716c"
  },
  {
    id: 13,
    nameAr: "محلل البنية التحتية",
    nameEn: "Infrastructure Analyst",
    specialtyAr: "الخدمات اللوجستية والتقنية في عمان",
    specialtyEn: "Logistics and Technical Services in Oman",
    contributionAr: "يقيم توفر الإنترنت والكهرباء والطرق اللازمة للمشروع في عمان.",
    contributionEn: "Evaluates the availability of internet, electricity, and roads needed for the project in Oman.",
    triggerAr: "عندما يتطلب المشروع بنية تحتية مادية أو رقمية قوية.",
    triggerEn: "When the project requires strong physical or digital infrastructure.",
    icon: "Building2",
    category: 'oman',
    color: "#475569"
  },
  {
    id: 14,
    nameAr: "محامي المستخدم العماني",
    nameEn: "Omani User Advocate",
    specialtyAr: "سلوك المستهلك العماني",
    specialtyEn: "Omani Consumer Behavior",
    contributionAr: "يركز على العادات والتقاليد وتفضيلات المستخدم في عمان.",
    contributionEn: "Focuses on customs, traditions, and user preferences in Oman.",
    triggerAr: "عند تصميم واجهة المستخدم أو تجربة الخدمة محلياً.",
    triggerEn: "When designing the user interface or service experience locally.",
    icon: "Users",
    category: 'oman',
    color: "#d946ef"
  },
  {
    id: 15,
    nameAr: "محلل القوة الشرائية",
    nameEn: "Purchasing Power Analyst",
    specialtyAr: "الاقتصاد المحلي والأسعار",
    specialtyEn: "Local Economy and Pricing",
    contributionAr: "يحدد الأسعار المناسبة للمواطن والمقيم في عمان.",
    contributionEn: "Determines appropriate prices for citizens and residents in Oman.",
    triggerAr: "عند تحديد استراتيجية التسعير للمنتج أو الخدمة.",
    triggerEn: "When determining the pricing strategy for the product or service.",
    icon: "Wallet",
    category: 'oman',
    color: "#84cc16"
  },
  {
    id: 16,
    nameAr: "استراتيجي الشراكات",
    nameEn: "Partnership Strategist",
    specialtyAr: "التعاون مع الجهات الحكومية والخاصة",
    specialtyEn: "Collaboration with Public and Private Sectors",
    contributionAr: "يقترح جهات عمانية (مثل أوكيو، عمانتل) يمكن الشراكة معها.",
    contributionEn: "Suggests Omani entities (e.g., OQ, Omantel) for potential partnerships.",
    triggerAr: "عند البحث عن دعم أو تكامل مع منظومة الأعمال العمانية.",
    triggerEn: "When looking for support or integration with the Omani business ecosystem.",
    icon: "Handshake",
    category: 'oman',
    color: "#0ea5e9"
  },
  {
    id: 17,
    nameAr: "محلل المناخ",
    nameEn: "Climate Analyst",
    specialtyAr: "تأثير البيئة والطقس في عمان",
    specialtyEn: "Impact of Environment and Weather in Oman",
    contributionAr: "يدرس كيف تؤثر الحرارة والرطوبة على المشروع.",
    contributionEn: "Studies how heat and humidity affect the project.",
    triggerAr: "عندما يكون للمشروع جانب مادي يتأثر بالطقس.",
    triggerEn: "When the project has a physical aspect affected by weather.",
    icon: "CloudSun",
    category: 'oman',
    color: "#f97316"
  },
  {
    id: 18,
    nameAr: "مخطط اللوجستيات",
    nameEn: "Logistics Planner",
    specialtyAr: "النقل والتوزيع في السلطنة",
    specialtyEn: "Transport and Distribution in the Sultanate",
    contributionAr: "يركز على سلاسل الإمداد والتوصيل بين المحافظات.",
    contributionEn: "Focuses on supply chains and delivery between governorates.",
    triggerAr: "عندما يتضمن المشروع توزيع سلع أو خدمات مادية.",
    triggerEn: "When the project involves distributing physical goods or services.",
    icon: "Truck",
    category: 'oman',
    color: "#4ade80"
  },
  {
    id: 19,
    nameAr: "مستشار التصنيع المحلي",
    nameEn: "Local Manufacturing Advisor",
    specialtyAr: "القيمة المحلية المضافة (ICV)",
    specialtyEn: "In-Country Value (ICV)",
    contributionAr: "يشجع على استخدام الموارد العمانية في الإنتاج.",
    contributionEn: "Encourages the use of Omani resources in production.",
    triggerAr: "عند التفكير في تصنيع المنتج محلياً بدل الاستيراد.",
    triggerEn: "When thinking about manufacturing the product locally instead of importing.",
    icon: "Factory",
    category: 'oman',
    color: "#fbbf24"
  },
  {
    id: 20,
    nameAr: "وكيل رؤية عمان 2040",
    nameEn: "Vision 2040 Alignment Agent",
    specialtyAr: "التوافق مع الأهداف الوطنية",
    specialtyEn: "Alignment with National Goals",
    contributionAr: "يضمن أن المشروع يخدم ركائز رؤية عمان 2040.",
    contributionEn: "Ensures the project serves the pillars of Oman Vision 2040.",
    triggerAr: "دائماً لضمان الاستدامة والقبول الحكومي.",
    triggerEn: "Always to ensure sustainability and government acceptance.",
    icon: "Target",
    category: 'oman',
    color: "#ef4444"
  }
];

export const TRANSLATIONS = {
  ar: {
    title: "Majlis AI – مجلس الأفكار الذكي",
    setup: "إعداد الجلسة",
    language: "اللغة",
    style: "أسلوب الحوار",
    mode: "وضع النقاش",
    participants: "نطاق المشاركين",
    start: "ابدأ الاجتماع",
    formal: "رسمي",
    omani: "لهجة عمانية",
    manual: "يدوي",
    auto: "تلقائي",
    all: "كل الفريق (20)",
    selected: "أعضاء مختارون",
    brainPool: "عقل الاجتماع",
    firstIdea: "فكرتي الأولى",
    suggestIdea: "ساعدني باقتراح أول فكرة",
    addToPool: "إضافة إلى عقل الاجتماع",
    continueDiscussion: "أكمل النقاش",
    developCurrent: "تطوير الفكرة الحالية",
    stopDiscussion: "إيقاف النقاش",
    startAuto: "ابدأ النقاش التلقائي",
    askAgent: "اسأل هذا الوكيل",
    isSuitable: "هل الفكرة مناسبة؟",
    suitable: "مناسبة",
    notSuitable: "غير مناسبة",
    duplicate: "مكرر",
    endMeeting: "إنهاء الاجتماع",
    summary: "ملخص الاجتماع",
    export: "تصدير / نسخ",
    feedback: "تقييم الوكلاء",
    relevance: "الملاءمة",
    contribution: "الجودة",
    comment: "تعليق",
    save: "حفظ",
    back: "رجوع",
    omanFeasibility: "قابلية التطبيق في سلطنة عمان",
    recommendations: "التوصيات",
    finalDecision: "القرار النهائي",
    noIdeaYet: "لم يتم إضافة أي فكرة بعد.",
    makePivot: "اجعلها محور النقاش",
    delete: "حذف",
    agentProfile: "ملف الوكيل",
    specialty: "التخصص",
    howContribute: "كيف سيساهم؟",
    whenIntervene: "متى يتدخل؟",
    loading: "جاري التفكير...",
    duplicateWarning: "هذه الفكرة مكررة، جرب تطويراً مختلفاً.",
    placeholderIdea: "اكتب موضوع الاجتماع هنا...",
    placeholderQuestion: "اسأل الوكيل شيئاً...",
    phase1Title: "المرحلة 1: نقاش الموضوع",
    phase2Title: "المرحلة 2: توليد فكرة",
    phase3Title: "المرحلة 3: نقاش الفكرة",
    agreedOnTopic: "اتفقنا على الموضوع",
    moveToNewIdea: "الانتقال لفكرة جديدة",
    topicPlaceholder: "ما هو موضوع اجتماعنا اليوم؟",
  },
  en: {
    title: "Majlis AI – Smart Idea Council",
    setup: "Session Setup",
    language: "Language",
    style: "Discussion Style",
    mode: "Discussion Mode",
    participants: "Participants Scope",
    start: "Start Meeting",
    formal: "Formal",
    omani: "Omani Dialect",
    manual: "Manual",
    auto: "Auto",
    all: "All Team (20)",
    selected: "Selected Members",
    brainPool: "Brain Pool",
    firstIdea: "Meeting Topic",
    suggestIdea: "Help me suggest the first idea",
    addToPool: "Add to Brain Pool",
    continueDiscussion: "Continue Discussion",
    developCurrent: "Develop Current Idea",
    stopDiscussion: "Stop Discussion",
    startAuto: "Start Auto Discussion",
    askAgent: "Ask this Agent",
    isSuitable: "Is the idea suitable?",
    suitable: "Suitable",
    notSuitable: "Not Suitable",
    duplicate: "Duplicate",
    endMeeting: "End Meeting",
    summary: "Meeting Summary",
    export: "Export / Copy",
    feedback: "Agent Feedback",
    relevance: "Relevance",
    contribution: "Contribution Quality",
    comment: "Comment",
    save: "Save",
    back: "Back",
    omanFeasibility: "Feasibility in Oman",
    recommendations: "Recommendations",
    finalDecision: "Final Decision",
    noIdeaYet: "No ideas added yet.",
    makePivot: "Make it Pivot",
    delete: "Delete",
    agentProfile: "Agent Profile",
    specialty: "Specialty",
    howContribute: "How will they contribute?",
    whenIntervene: "When do they intervene?",
    loading: "Thinking...",
    duplicateWarning: "This idea is a duplicate, try a different development.",
    placeholderIdea: "Write the meeting topic here...",
    placeholderQuestion: "Ask the agent something...",
    phase1Title: "Phase 1: Topic Discussion",
    phase2Title: "Phase 2: Idea Generation",
    phase3Title: "Phase 3: Idea Discussion",
    agreedOnTopic: "Agreed on Topic",
    moveToNewIdea: "Move to New Idea",
    topicPlaceholder: "What is our meeting topic today?",
  }
};
